import type { PhraseCategory } from "../../../lib/types";

interface RawPhrase {
  text: string;
  category: PhraseCategory;
}

/**
 * Raw phrase bank. Difficulty is computed automatically at runtime
 * via calculatePhraseDifficulty in phrases.ts.
 *
 * Guidelines for adding phrases:
 * - ALL CAPS, no punctuation except hyphens and apostrophes
 * - Should be recognizable / guessable by a general audience
 * - Aim for a mix of short (2-3 words) and long (4-6 words) phrases
 * - No duplicates across categories
 */
export const RAW_PHRASES: RawPhrase[] = [
  // ──────────────────────────────────────────
  // Movie Titles
  // ──────────────────────────────────────────
  { text: "THE SHAWSHANK REDEMPTION", category: "Movie Titles" },
  { text: "BACK TO THE FUTURE", category: "Movie Titles" },
  { text: "THE WIZARD OF OZ", category: "Movie Titles" },
  { text: "JURASSIC PARK", category: "Movie Titles" },
  { text: "THE LION KING", category: "Movie Titles" },
  { text: "FORREST GUMP", category: "Movie Titles" },
  { text: "THE DARK KNIGHT", category: "Movie Titles" },
  { text: "PULP FICTION", category: "Movie Titles" },
  { text: "FINDING NEMO", category: "Movie Titles" },
  { text: "THE MATRIX", category: "Movie Titles" },
  { text: "TOY STORY", category: "Movie Titles" },
  { text: "FROZEN", category: "Movie Titles" },
  { text: "STAR WARS", category: "Movie Titles" },
  { text: "HOME ALONE", category: "Movie Titles" },
  { text: "THE LITTLE MERMAID", category: "Movie Titles" },
  { text: "CARS", category: "Movie Titles" },
  { text: "MOANA", category: "Movie Titles" },
  { text: "SHREK", category: "Movie Titles" },
  { text: "UP", category: "Movie Titles" },
  { text: "INSIDE OUT", category: "Movie Titles" },
  { text: "COCO", category: "Movie Titles" },
  { text: "ALADDIN", category: "Movie Titles" },
  { text: "RATATOUILLE", category: "Movie Titles" },
  { text: "BEAUTY AND THE BEAST", category: "Movie Titles" },
  { text: "THE INCREDIBLES", category: "Movie Titles" },
  { text: "GHOSTBUSTERS", category: "Movie Titles" },
  { text: "MONSTERS INC", category: "Movie Titles" },
  { text: "PETER PAN", category: "Movie Titles" },
  { text: "BAMBI", category: "Movie Titles" },
  { text: "LILO AND STITCH", category: "Movie Titles" },
  { text: "TANGLED", category: "Movie Titles" },
  { text: "BIG HERO SIX", category: "Movie Titles" },
  { text: "WRECK IT RALPH", category: "Movie Titles" },
  { text: "THE JUNGLE BOOK", category: "Movie Titles" },
  { text: "HAPPY FEET", category: "Movie Titles" },
  { text: "ICE AGE", category: "Movie Titles" },
  { text: "THE PARENT TRAP", category: "Movie Titles" },
  { text: "NIGHT AT THE MUSEUM", category: "Movie Titles" },
  { text: "PIRATES OF THE CARIBBEAN", category: "Movie Titles" },
  { text: "MARY POPPINS", category: "Movie Titles" },
  { text: "WILLY WONKA", category: "Movie Titles" },
  { text: "INDIANA JONES", category: "Movie Titles" },
  { text: "TOP GUN", category: "Movie Titles" },
  { text: "THE KARATE KID", category: "Movie Titles" },
  { text: "MULAN", category: "Movie Titles" },
  { text: "BRAVE", category: "Movie Titles" },
  { text: "SOUL", category: "Movie Titles" },
  { text: "LUCA", category: "Movie Titles" },
  { text: "TURNING RED", category: "Movie Titles" },
  { text: "ENCANTO", category: "Movie Titles" },

  // ──────────────────────────────────────────
  // Famous Quotes
  // ──────────────────────────────────────────
  { text: "TO BE OR NOT TO BE", category: "Famous Quotes" },
  { text: "I THINK THEREFORE I AM", category: "Famous Quotes" },
  { text: "HOUSTON WE HAVE A PROBLEM", category: "Famous Quotes" },
  { text: "MAY THE FORCE BE WITH YOU", category: "Famous Quotes" },
  { text: "THAT IS ONE SMALL STEP FOR MAN", category: "Famous Quotes" },
  { text: "HERE LOOKING AT YOU KID", category: "Famous Quotes" },
  { text: "LIFE IS LIKE A BOX OF CHOCOLATES", category: "Famous Quotes" },
  { text: "YOU CANT HANDLE THE TRUTH", category: "Famous Quotes" },
  { text: "ELEMENTARY MY DEAR WATSON", category: "Famous Quotes" },
  { text: "I WILL BE BACK", category: "Famous Quotes" },
  { text: "JUST KEEP SWIMMING", category: "Famous Quotes" },
  { text: "TO INFINITY AND BEYOND", category: "Famous Quotes" },
  { text: "LET IT GO", category: "Famous Quotes" },
  { text: "THERE IS NO PLACE LIKE HOME", category: "Famous Quotes" },
  { text: "HAKUNA MATATA", category: "Famous Quotes" },
  { text: "OH THE PLACES YOU WILL GO", category: "Famous Quotes" },
  { text: "I AM THE GREATEST", category: "Famous Quotes" },
  { text: "BE THE CHANGE YOU WISH TO SEE", category: "Famous Quotes" },
  { text: "ALL YOU NEED IS LOVE", category: "Famous Quotes" },
  { text: "JUST DO IT", category: "Famous Quotes" },
  { text: "THATS ALL FOLKS", category: "Famous Quotes" },
  { text: "I HAVE A DREAM", category: "Famous Quotes" },
  { text: "KNOWLEDGE IS POWER", category: "Famous Quotes" },
  { text: "PRACTICE MAKES PERFECT", category: "Famous Quotes" },
  { text: "LESS IS MORE", category: "Famous Quotes" },
  { text: "ACTIONS SPEAK LOUDER THAN WORDS", category: "Famous Quotes" },
  { text: "THE SHOW MUST GO ON", category: "Famous Quotes" },
  { text: "WITH GREAT POWER COMES GREAT RESPONSIBILITY", category: "Famous Quotes" },
  { text: "I SEE DEAD PEOPLE", category: "Famous Quotes" },
  { text: "KEEP CALM AND CARRY ON", category: "Famous Quotes" },
  { text: "LIVE LONG AND PROSPER", category: "Famous Quotes" },
  { text: "BEAM ME UP", category: "Famous Quotes" },
  { text: "ITS A WONDERFUL LIFE", category: "Famous Quotes" },
  { text: "WE ARE THE CHAMPIONS", category: "Famous Quotes" },
  { text: "HERE COMES THE SUN", category: "Famous Quotes" },
  { text: "ONE SMALL STEP FOR MANKIND", category: "Famous Quotes" },
  { text: "YOU ARE WHAT YOU EAT", category: "Famous Quotes" },
  { text: "LAUGHTER IS THE BEST MEDICINE", category: "Famous Quotes" },
  { text: "TIME FLIES WHEN YOU ARE HAVING FUN", category: "Famous Quotes" },
  { text: "HOME IS WHERE THE HEART IS", category: "Famous Quotes" },

  // ──────────────────────────────────────────
  // Song Lyrics
  // ──────────────────────────────────────────
  { text: "DONT STOP BELIEVING", category: "Song Lyrics" },
  { text: "BOHEMIAN RHAPSODY", category: "Song Lyrics" },
  { text: "IMAGINE ALL THE PEOPLE", category: "Song Lyrics" },
  { text: "WE WILL ROCK YOU", category: "Song Lyrics" },
  { text: "SWEET HOME ALABAMA", category: "Song Lyrics" },
  { text: "STAIRWAY TO HEAVEN", category: "Song Lyrics" },
  { text: "EVERY BREATH YOU TAKE", category: "Song Lyrics" },
  { text: "DANCING IN THE MOONLIGHT", category: "Song Lyrics" },
  { text: "THUNDER AND LIGHTNING", category: "Song Lyrics" },
  { text: "WALKING ON SUNSHINE", category: "Song Lyrics" },
  { text: "HAPPY BIRTHDAY TO YOU", category: "Song Lyrics" },
  { text: "TWINKLE TWINKLE LITTLE STAR", category: "Song Lyrics" },
  { text: "OLD MACDONALD HAD A FARM", category: "Song Lyrics" },
  { text: "ROW ROW ROW YOUR BOAT", category: "Song Lyrics" },
  { text: "JINGLE BELLS", category: "Song Lyrics" },
  { text: "LET IT BE", category: "Song Lyrics" },
  { text: "SOMEWHERE OVER THE RAINBOW", category: "Song Lyrics" },
  { text: "WHAT A WONDERFUL WORLD", category: "Song Lyrics" },
  { text: "YELLOW SUBMARINE", category: "Song Lyrics" },
  { text: "UNDER THE SEA", category: "Song Lyrics" },
  { text: "A WHOLE NEW WORLD", category: "Song Lyrics" },
  { text: "CANT STOP THE FEELING", category: "Song Lyrics" },
  { text: "SHAKE IT OFF", category: "Song Lyrics" },
  { text: "DANCING QUEEN", category: "Song Lyrics" },
  { text: "TAKE ME HOME COUNTRY ROADS", category: "Song Lyrics" },
  { text: "SWEET CAROLINE", category: "Song Lyrics" },
  { text: "HERE COMES THE BRIDE", category: "Song Lyrics" },
  { text: "LEAN ON ME", category: "Song Lyrics" },
  { text: "THREE LITTLE BIRDS", category: "Song Lyrics" },
  { text: "RING AROUND THE ROSIE", category: "Song Lyrics" },
  { text: "LONDON BRIDGE IS FALLING DOWN", category: "Song Lyrics" },
  { text: "HEAD SHOULDERS KNEES AND TOES", category: "Song Lyrics" },
  { text: "IF YOU ARE HAPPY AND YOU KNOW IT", category: "Song Lyrics" },
  { text: "THE WHEELS ON THE BUS", category: "Song Lyrics" },
  { text: "DO RE MI FA SOL LA TI DO", category: "Song Lyrics" },
  { text: "SILENT NIGHT HOLY NIGHT", category: "Song Lyrics" },
  { text: "FROSTY THE SNOWMAN", category: "Song Lyrics" },
  { text: "RUDOLPH THE RED NOSED REINDEER", category: "Song Lyrics" },
  { text: "ITSY BITSY SPIDER", category: "Song Lyrics" },
  { text: "YOU ARE MY SUNSHINE", category: "Song Lyrics" },

  // ──────────────────────────────────────────
  // Food & Drink
  // ──────────────────────────────────────────
  { text: "PEANUT BUTTER AND JELLY", category: "Food & Drink" },
  { text: "CHICKEN NOODLE SOUP", category: "Food & Drink" },
  { text: "STRAWBERRY SHORTCAKE", category: "Food & Drink" },
  { text: "MACARONI AND CHEESE", category: "Food & Drink" },
  { text: "CHOCOLATE CHIP COOKIES", category: "Food & Drink" },
  { text: "BANANA SPLIT SUNDAE", category: "Food & Drink" },
  { text: "FRESH SQUEEZED LEMONADE", category: "Food & Drink" },
  { text: "GRILLED CHEESE SANDWICH", category: "Food & Drink" },
  { text: "PEPPERONI PIZZA", category: "Food & Drink" },
  { text: "BLUEBERRY PANCAKES", category: "Food & Drink" },
  { text: "HOT DOG", category: "Food & Drink" },
  { text: "ICE CREAM", category: "Food & Drink" },
  { text: "APPLE PIE", category: "Food & Drink" },
  { text: "FRENCH FRIES", category: "Food & Drink" },
  { text: "COTTON CANDY", category: "Food & Drink" },
  { text: "ROOT BEER FLOAT", category: "Food & Drink" },
  { text: "CORN ON THE COB", category: "Food & Drink" },
  { text: "CHEESE PIZZA", category: "Food & Drink" },
  { text: "FISH AND CHIPS", category: "Food & Drink" },
  { text: "RICE AND BEANS", category: "Food & Drink" },
  { text: "SCRAMBLED EGGS", category: "Food & Drink" },
  { text: "MASHED POTATOES", category: "Food & Drink" },
  { text: "FRIED CHICKEN", category: "Food & Drink" },
  { text: "TACO TUESDAY", category: "Food & Drink" },
  { text: "SPAGHETTI AND MEATBALLS", category: "Food & Drink" },
  { text: "PUMPKIN PIE", category: "Food & Drink" },
  { text: "CANDY CORN", category: "Food & Drink" },
  { text: "JELLY BEANS", category: "Food & Drink" },
  { text: "FRUIT SALAD", category: "Food & Drink" },
  { text: "TRAIL MIX", category: "Food & Drink" },
  { text: "CHICKEN TENDERS", category: "Food & Drink" },
  { text: "ONION RINGS", category: "Food & Drink" },
  { text: "GARLIC BREAD", category: "Food & Drink" },
  { text: "TOMATO SOUP", category: "Food & Drink" },
  { text: "PEANUT BUTTER CUP", category: "Food & Drink" },
  { text: "ORANGE JUICE", category: "Food & Drink" },
  { text: "HOT CHOCOLATE", category: "Food & Drink" },
  { text: "BUTTERED POPCORN", category: "Food & Drink" },
  { text: "GLAZED DONUT", category: "Food & Drink" },
  { text: "CINNAMON ROLL", category: "Food & Drink" },
  { text: "BIRTHDAY CAKE", category: "Food & Drink" },
  { text: "GUMMY BEARS", category: "Food & Drink" },
  { text: "CHOCOLATE MILK", category: "Food & Drink" },
  { text: "WAFFLES AND SYRUP", category: "Food & Drink" },
  { text: "BAGEL AND CREAM CHEESE", category: "Food & Drink" },

  // ──────────────────────────────────────────
  // Places
  // ──────────────────────────────────────────
  { text: "GRAND CANYON", category: "Places" },
  { text: "STATUE OF LIBERTY", category: "Places" },
  { text: "GREAT WALL OF CHINA", category: "Places" },
  { text: "EIFFEL TOWER", category: "Places" },
  { text: "MOUNT EVEREST", category: "Places" },
  { text: "GOLDEN GATE BRIDGE", category: "Places" },
  { text: "NIAGARA FALLS", category: "Places" },
  { text: "CENTRAL PARK", category: "Places" },
  { text: "TIMES SQUARE", category: "Places" },
  { text: "SILICON VALLEY", category: "Places" },
  { text: "DISNEY WORLD", category: "Places" },
  { text: "WHITE HOUSE", category: "Places" },
  { text: "NORTH POLE", category: "Places" },
  { text: "OUTER SPACE", category: "Places" },
  { text: "RAIN FOREST", category: "Places" },
  { text: "MOUNT RUSHMORE", category: "Places" },
  { text: "ATLANTIC OCEAN", category: "Places" },
  { text: "PACIFIC OCEAN", category: "Places" },
  { text: "SAHARA DESERT", category: "Places" },
  { text: "GREAT BARRIER REEF", category: "Places" },
  { text: "SOUTH POLE", category: "Places" },
  { text: "AMAZON RIVER", category: "Places" },
  { text: "ROCKY MOUNTAINS", category: "Places" },
  { text: "YELLOWSTONE PARK", category: "Places" },
  { text: "HOLLYWOOD HILLS", category: "Places" },
  { text: "WALL STREET", category: "Places" },
  { text: "LONDON BRIDGE", category: "Places" },
  { text: "BIG BEN", category: "Places" },
  { text: "GREAT LAKES", category: "Places" },
  { text: "EMPIRE STATE BUILDING", category: "Places" },
  { text: "LEANING TOWER OF PISA", category: "Places" },
  { text: "THE BERMUDA TRIANGLE", category: "Places" },
  { text: "ELLIS ISLAND", category: "Places" },
  { text: "PEARL HARBOR", category: "Places" },
  { text: "CAPE COD", category: "Places" },
  { text: "DEATH VALLEY", category: "Places" },
  { text: "LAKE MICHIGAN", category: "Places" },
  { text: "NILE RIVER", category: "Places" },
  { text: "ROUTE SIXTY SIX", category: "Places" },
  { text: "BROADWAY THEATRE", category: "Places" },

  // ──────────────────────────────────────────
  // Idioms
  // ──────────────────────────────────────────
  { text: "BREAK A LEG", category: "Idioms" },
  { text: "PIECE OF CAKE", category: "Idioms" },
  { text: "BITE THE BULLET", category: "Idioms" },
  { text: "UNDER THE WEATHER", category: "Idioms" },
  { text: "HIT THE NAIL ON THE HEAD", category: "Idioms" },
  { text: "COST AN ARM AND A LEG", category: "Idioms" },
  { text: "BLESSING IN DISGUISE", category: "Idioms" },
  { text: "ONCE IN A BLUE MOON", category: "Idioms" },
  { text: "BURNING THE MIDNIGHT OIL", category: "Idioms" },
  { text: "THE BEST OF BOTH WORLDS", category: "Idioms" },
  { text: "ON TOP OF THE WORLD", category: "Idioms" },
  { text: "EASY AS PIE", category: "Idioms" },
  { text: "HOLD YOUR HORSES", category: "Idioms" },
  { text: "LET THE CAT OUT OF THE BAG", category: "Idioms" },
  { text: "RAINING CATS AND DOGS", category: "Idioms" },
  { text: "SPILL THE BEANS", category: "Idioms" },
  { text: "A PENNY FOR YOUR THOUGHTS", category: "Idioms" },
  { text: "BARKING UP THE WRONG TREE", category: "Idioms" },
  { text: "BITE OFF MORE THAN YOU CAN CHEW", category: "Idioms" },
  { text: "BETTER LATE THAN NEVER", category: "Idioms" },
  { text: "CALL IT A DAY", category: "Idioms" },
  { text: "CURIOSITY KILLED THE CAT", category: "Idioms" },
  { text: "CUT TO THE CHASE", category: "Idioms" },
  { text: "DONT CRY OVER SPILLED MILK", category: "Idioms" },
  { text: "EVERY CLOUD HAS A SILVER LINING", category: "Idioms" },
  { text: "GET OUT OF HAND", category: "Idioms" },
  { text: "GO THE EXTRA MILE", category: "Idioms" },
  { text: "HANG IN THERE", category: "Idioms" },
  { text: "HIT THE ROAD", category: "Idioms" },
  { text: "IN HOT WATER", category: "Idioms" },
  { text: "KILL TWO BIRDS WITH ONE STONE", category: "Idioms" },
  { text: "MISS THE BOAT", category: "Idioms" },
  { text: "NO PAIN NO GAIN", category: "Idioms" },
  { text: "ON THIN ICE", category: "Idioms" },
  { text: "PULL SOMEONES LEG", category: "Idioms" },
  { text: "STEAL THE SHOW", category: "Idioms" },
  { text: "THE BALL IS IN YOUR COURT", category: "Idioms" },
  { text: "THROW IN THE TOWEL", category: "Idioms" },
  { text: "WHEN PIGS FLY", category: "Idioms" },
  { text: "YOU HIT IT OUT OF THE PARK", category: "Idioms" },

  // ──────────────────────────────────────────
  // Pop Culture
  // ──────────────────────────────────────────
  { text: "GAME OF THRONES", category: "Pop Culture" },
  { text: "STRANGER THINGS", category: "Pop Culture" },
  { text: "TAYLOR SWIFT ERA", category: "Pop Culture" },
  { text: "SUPER MARIO BROTHERS", category: "Pop Culture" },
  { text: "HARRY POTTER", category: "Pop Culture" },
  { text: "STAR WARS SAGA", category: "Pop Culture" },
  { text: "POKEMON MASTER", category: "Pop Culture" },
  { text: "MINECRAFT WORLD", category: "Pop Culture" },
  { text: "SOCIAL MEDIA INFLUENCER", category: "Pop Culture" },
  { text: "VIRAL INTERNET CHALLENGE", category: "Pop Culture" },
  { text: "SPONGEBOB SQUAREPANTS", category: "Pop Culture" },
  { text: "MICKEY MOUSE", category: "Pop Culture" },
  { text: "BUGS BUNNY", category: "Pop Culture" },
  { text: "SCOOBY DOO", category: "Pop Culture" },
  { text: "PEANUTS COMIC STRIP", category: "Pop Culture" },
  { text: "WINNIE THE POOH", category: "Pop Culture" },
  { text: "SESAME STREET", category: "Pop Culture" },
  { text: "THE AVENGERS", category: "Pop Culture" },
  { text: "SPIDER MAN", category: "Pop Culture" },
  { text: "BATMAN AND ROBIN", category: "Pop Culture" },
  { text: "WONDER WOMAN", category: "Pop Culture" },
  { text: "SUPER SMASH BROTHERS", category: "Pop Culture" },
  { text: "ANIMAL CROSSING", category: "Pop Culture" },
  { text: "FORTNITE BATTLE ROYALE", category: "Pop Culture" },
  { text: "ROBLOX UNIVERSE", category: "Pop Culture" },
  { text: "THE SIMPSONS", category: "Pop Culture" },
  { text: "PEPPA PIG", category: "Pop Culture" },
  { text: "PAW PATROL", category: "Pop Culture" },
  { text: "DORA THE EXPLORER", category: "Pop Culture" },
  { text: "BLUE CLUES", category: "Pop Culture" },
  { text: "SUPER MARIO KART", category: "Pop Culture" },
  { text: "LEGEND OF ZELDA", category: "Pop Culture" },
  { text: "AMONG US IMPOSTER", category: "Pop Culture" },
  { text: "HELLO KITTY", category: "Pop Culture" },
  { text: "TEENAGE MUTANT NINJA TURTLES", category: "Pop Culture" },
  { text: "POKEMON GO", category: "Pop Culture" },
  { text: "TOM AND JERRY", category: "Pop Culture" },
  { text: "LOONEY TUNES", category: "Pop Culture" },
  { text: "CHARLIE BROWN", category: "Pop Culture" },
  { text: "DR SEUSS", category: "Pop Culture" },

  // ──────────────────────────────────────────
  // Sports
  // ──────────────────────────────────────────
  { text: "WORLD SERIES CHAMPION", category: "Sports" },
  { text: "TOUCHDOWN CELEBRATION", category: "Sports" },
  { text: "SLAM DUNK CONTEST", category: "Sports" },
  { text: "OLYMPIC GOLD MEDAL", category: "Sports" },
  { text: "GRAND SLAM WINNER", category: "Sports" },
  { text: "HOLE IN ONE", category: "Sports" },
  { text: "SUPER BOWL HALFTIME", category: "Sports" },
  { text: "PENALTY SHOOTOUT", category: "Sports" },
  { text: "TRIPLE CROWN WINNER", category: "Sports" },
  { text: "MARATHON FINISH LINE", category: "Sports" },
  { text: "HOME RUN", category: "Sports" },
  { text: "FREE THROW", category: "Sports" },
  { text: "FIELD GOAL", category: "Sports" },
  { text: "FIRST PLACE", category: "Sports" },
  { text: "GOLD MEDAL", category: "Sports" },
  { text: "HIGH SCORE", category: "Sports" },
  { text: "THREE POINTER", category: "Sports" },
  { text: "WORLD CUP SOCCER", category: "Sports" },
  { text: "BATTING PRACTICE", category: "Sports" },
  { text: "SOCCER GOAL", category: "Sports" },
  { text: "ICE SKATING RINK", category: "Sports" },
  { text: "SWIMMING RELAY", category: "Sports" },
  { text: "TRACK AND FIELD", category: "Sports" },
  { text: "BASEBALL DIAMOND", category: "Sports" },
  { text: "BASKETBALL COURT", category: "Sports" },
  { text: "TENNIS MATCH POINT", category: "Sports" },
  { text: "FOOTBALL SEASON", category: "Sports" },
  { text: "GAME WINNING SHOT", category: "Sports" },
  { text: "OPENING CEREMONY", category: "Sports" },
  { text: "RELAY RACE", category: "Sports" },
  { text: "STARTING LINEUP", category: "Sports" },
  { text: "TIED GAME", category: "Sports" },
  { text: "VICTORY LAP", category: "Sports" },
  { text: "DOUBLE PLAY", category: "Sports" },
  { text: "HAT TRICK", category: "Sports" },
  { text: "PHOTO FINISH", category: "Sports" },
  { text: "SUDDEN DEATH OVERTIME", category: "Sports" },
  { text: "STANDING OVATION", category: "Sports" },
  { text: "INSTANT REPLAY", category: "Sports" },
  { text: "PLAY BALL", category: "Sports" },

  // ──────────────────────────────────────────
  // Science & Nature
  // ──────────────────────────────────────────
  { text: "NORTHERN LIGHTS AURORA", category: "Science & Nature" },
  { text: "MILKY WAY GALAXY", category: "Science & Nature" },
  { text: "THEORY OF RELATIVITY", category: "Science & Nature" },
  { text: "PHOTOSYNTHESIS PROCESS", category: "Science & Nature" },
  { text: "PERIODIC TABLE OF ELEMENTS", category: "Science & Nature" },
  { text: "RAINFOREST ECOSYSTEM", category: "Science & Nature" },
  { text: "SOLAR ECLIPSE", category: "Science & Nature" },
  { text: "CORAL REEF HABITAT", category: "Science & Nature" },
  { text: "GRAVITATIONAL PULL", category: "Science & Nature" },
  { text: "VOLCANIC ERUPTION", category: "Science & Nature" },
  { text: "FULL MOON", category: "Science & Nature" },
  { text: "RAIN CLOUD", category: "Science & Nature" },
  { text: "SHOOTING STAR", category: "Science & Nature" },
  { text: "SOLAR SYSTEM", category: "Science & Nature" },
  { text: "MOTHER NATURE", category: "Science & Nature" },
  { text: "NORTH STAR", category: "Science & Nature" },
  { text: "FOSSIL BONES", category: "Science & Nature" },
  { text: "OUTER PLANET", category: "Science & Nature" },
  { text: "GIANT REDWOOD TREE", category: "Science & Nature" },
  { text: "FOOD CHAIN", category: "Science & Nature" },
  { text: "ANIMAL MIGRATION", category: "Science & Nature" },
  { text: "DINOSAUR FOSSIL", category: "Science & Nature" },
  { text: "WATER CYCLE", category: "Science & Nature" },
  { text: "LIGHTNING BOLT", category: "Science & Nature" },
  { text: "TORNADO ALLEY", category: "Science & Nature" },
  { text: "PLANET EARTH", category: "Science & Nature" },
  { text: "RINGS OF SATURN", category: "Science & Nature" },
  { text: "TIDAL WAVE", category: "Science & Nature" },
  { text: "POLAR ICE CAP", category: "Science & Nature" },
  { text: "DEEP BLUE SEA", category: "Science & Nature" },
  { text: "SPRING TIME FLOWERS", category: "Science & Nature" },
  { text: "AUTUMN LEAVES", category: "Science & Nature" },
  { text: "OCEAN CURRENT", category: "Science & Nature" },
  { text: "STARRY NIGHT SKY", category: "Science & Nature" },
  { text: "DOUBLE RAINBOW", category: "Science & Nature" },
  { text: "METEOR SHOWER", category: "Science & Nature" },
  { text: "SNOW FLAKE", category: "Science & Nature" },
  { text: "HIBERNATION", category: "Science & Nature" },
  { text: "BALD EAGLE", category: "Science & Nature" },
  { text: "GRIZZLY BEAR", category: "Science & Nature" },

  // ──────────────────────────────────────────
  // History
  // ──────────────────────────────────────────
  { text: "DECLARATION OF INDEPENDENCE", category: "History" },
  { text: "ANCIENT EGYPTIAN PYRAMID", category: "History" },
  { text: "INDUSTRIAL REVOLUTION", category: "History" },
  { text: "RENAISSANCE MASTERPIECE", category: "History" },
  { text: "ROMAN COLOSSEUM", category: "History" },
  { text: "SILK ROAD TRADE ROUTE", category: "History" },
  { text: "BOSTON TEA PARTY", category: "History" },
  { text: "WRIGHT BROTHERS FLIGHT", category: "History" },
  { text: "MOON LANDING MISSION", category: "History" },
  { text: "CIVIL RIGHTS MOVEMENT", category: "History" },
  { text: "GOLD RUSH", category: "History" },
  { text: "WILD WEST", category: "History" },
  { text: "ICE AGE ERA", category: "History" },
  { text: "STONE AGE", category: "History" },
  { text: "IRON AGE", category: "History" },
  { text: "FIRST PRESIDENT", category: "History" },
  { text: "LIBERTY BELL", category: "History" },
  { text: "STAR SPANGLED BANNER", category: "History" },
  { text: "COVERED WAGON TRAIL", category: "History" },
  { text: "PONY EXPRESS RIDER", category: "History" },
  { text: "PIRATE TREASURE MAP", category: "History" },
  { text: "KNIGHTS OF THE ROUND TABLE", category: "History" },
  { text: "TROJAN HORSE", category: "History" },
  { text: "ROBIN HOOD", category: "History" },
  { text: "KING ARTHUR", category: "History" },
  { text: "ANCIENT ROME", category: "History" },
  { text: "MEDIEVAL CASTLE", category: "History" },
  { text: "MAIDEN VOYAGE", category: "History" },
  { text: "FIRST AIRPLANE", category: "History" },
  { text: "TRANSCONTINENTAL RAILROAD", category: "History" },
  { text: "UNDERGROUND RAILROAD", category: "History" },
  { text: "LEWIS AND CLARK", category: "History" },
  { text: "PAUL REVERE RIDE", category: "History" },
  { text: "BILL OF RIGHTS", category: "History" },
  { text: "CONSTITUTION", category: "History" },
  { text: "AMERICAN REVOLUTION", category: "History" },
  { text: "ANCIENT GREECE", category: "History" },
  { text: "VIKING SHIP", category: "History" },
  { text: "SAMURAI WARRIOR", category: "History" },
  { text: "MODEL T FORD", category: "History" },

  // ──────────────────────────────────────────
  // Movie Titles (new batch)
  // ──────────────────────────────────────────
  { text: "THE GODFATHER", category: "Movie Titles" },
  { text: "TITANIC", category: "Movie Titles" },
  { text: "THE BREAKFAST CLUB", category: "Movie Titles" },
  { text: "RAIDERS OF THE LOST ARK", category: "Movie Titles" },
  { text: "THE SOUND OF MUSIC", category: "Movie Titles" },
  { text: "GREASE", category: "Movie Titles" },
  { text: "DIRTY DANCING", category: "Movie Titles" },
  { text: "THE PRINCESS BRIDE", category: "Movie Titles" },
  { text: "FERRIS BUELLERS DAY OFF", category: "Movie Titles" },
  { text: "JAWS", category: "Movie Titles" },
  { text: "ROCKY", category: "Movie Titles" },
  { text: "E T THE EXTRA TERRESTRIAL", category: "Movie Titles" },
  { text: "GOOD WILL HUNTING", category: "Movie Titles" },
  { text: "THE SILENCE OF THE LAMBS", category: "Movie Titles" },
  { text: "SCHINDLERS LIST", category: "Movie Titles" },
  { text: "BRAVEHEART", category: "Movie Titles" },
  { text: "GLADIATOR", category: "Movie Titles" },
  { text: "INCEPTION", category: "Movie Titles" },
  { text: "AVATAR", category: "Movie Titles" },
  { text: "BLACK PANTHER", category: "Movie Titles" },
  { text: "WALL-E", category: "Movie Titles" },
  { text: "A BUGS LIFE", category: "Movie Titles" },
  { text: "THE NOTEBOOK", category: "Movie Titles" },
  { text: "CATCH ME IF YOU CAN", category: "Movie Titles" },
  { text: "THE DEPARTED", category: "Movie Titles" },
  { text: "SAVING PRIVATE RYAN", category: "Movie Titles" },
  { text: "FIGHT CLUB", category: "Movie Titles" },
  { text: "THE SIXTH SENSE", category: "Movie Titles" },
  { text: "GROUNDHOG DAY", category: "Movie Titles" },
  { text: "THE TRUMAN SHOW", category: "Movie Titles" },
  { text: "LEGALLY BLONDE", category: "Movie Titles" },
  { text: "MEAN GIRLS", category: "Movie Titles" },
  { text: "CLUELESS", category: "Movie Titles" },
  { text: "THE LION THE WITCH AND THE WARDROBE", category: "Movie Titles" },
  { text: "CHARLIE AND THE CHOCOLATE FACTORY", category: "Movie Titles" },
  { text: "HONEY I SHRUNK THE KIDS", category: "Movie Titles" },
  { text: "MRS DOUBTFIRE", category: "Movie Titles" },
  { text: "JUMANJI", category: "Movie Titles" },
  { text: "THE SANDLOT", category: "Movie Titles" },
  { text: "A LEAGUE OF THEIR OWN", category: "Movie Titles" },

  // ──────────────────────────────────────────
  // Food & Drink (new batch)
  // ──────────────────────────────────────────
  { text: "CAESAR SALAD", category: "Food & Drink" },
  { text: "BANANA BREAD", category: "Food & Drink" },
  { text: "CHICKEN POT PIE", category: "Food & Drink" },
  { text: "BEEF STEW", category: "Food & Drink" },
  { text: "LOBSTER TAIL", category: "Food & Drink" },
  { text: "SHRIMP SCAMPI", category: "Food & Drink" },
  { text: "BUFFALO WINGS", category: "Food & Drink" },
  { text: "NACHOS AND CHEESE", category: "Food & Drink" },
  { text: "CLAM CHOWDER", category: "Food & Drink" },
  { text: "CHICKEN PARMESAN", category: "Food & Drink" },
  { text: "EGGS BENEDICT", category: "Food & Drink" },
  { text: "AVOCADO TOAST", category: "Food & Drink" },
  { text: "PULLED PORK SANDWICH", category: "Food & Drink" },
  { text: "FILET MIGNON", category: "Food & Drink" },
  { text: "CREME BRULEE", category: "Food & Drink" },
  { text: "TIRAMISU", category: "Food & Drink" },
  { text: "CLUB SANDWICH", category: "Food & Drink" },
  { text: "BEEF WELLINGTON", category: "Food & Drink" },
  { text: "LAMB CHOPS", category: "Food & Drink" },
  { text: "TRUFFLE FRIES", category: "Food & Drink" },
  { text: "BLUEBERRY MUFFIN", category: "Food & Drink" },
  { text: "ICE CREAM SUNDAE", category: "Food & Drink" },
  { text: "FRENCH TOAST", category: "Food & Drink" },
  { text: "BAKED POTATO", category: "Food & Drink" },
  { text: "TUNA CASSEROLE", category: "Food & Drink" },
  { text: "MAPLE GLAZED SALMON", category: "Food & Drink" },
  { text: "DUCK A L'ORANGE", category: "Food & Drink" },
  { text: "EGGS OVER EASY", category: "Food & Drink" },
  { text: "MASHED POTATOES AND GRAVY", category: "Food & Drink" },
  { text: "CHICKEN FRIED STEAK", category: "Food & Drink" },
  { text: "BISCUITS AND GRAVY", category: "Food & Drink" },
  { text: "KEY LIME PIE", category: "Food & Drink" },
  { text: "PEACH COBBLER", category: "Food & Drink" },
  { text: "EGGS AND BACON", category: "Food & Drink" },
  { text: "GRILLED SALMON", category: "Food & Drink" },
  { text: "MUSHROOM RISOTTO", category: "Food & Drink" },
  { text: "SOURDOUGH BREAD", category: "Food & Drink" },
  { text: "CHOCOLATE FONDUE", category: "Food & Drink" },
  { text: "SWEET POTATO FRIES", category: "Food & Drink" },
  { text: "LOADED BAKED POTATO", category: "Food & Drink" },

  // ──────────────────────────────────────────
  // Famous Quotes (new batch)
  // ──────────────────────────────────────────
  { text: "WE THE PEOPLE", category: "Famous Quotes" },
  { text: "GIVE ME LIBERTY OR GIVE ME DEATH", category: "Famous Quotes" },
  { text: "LET THEM EAT CAKE", category: "Famous Quotes" },
  { text: "THE ONLY THING WE HAVE TO FEAR", category: "Famous Quotes" },
  { text: "I AM YOUR FATHER", category: "Famous Quotes" },
  { text: "SHOW ME THE MONEY", category: "Famous Quotes" },
  { text: "NOBODY PUTS BABY IN A CORNER", category: "Famous Quotes" },
  { text: "FRANKLY MY DEAR I DONT GIVE A DAMN", category: "Famous Quotes" },
  { text: "YOU SHALL NOT PASS", category: "Famous Quotes" },
  { text: "WINTER IS COMING", category: "Famous Quotes" },
  { text: "AFTER ALL TOMORROW IS ANOTHER DAY", category: "Famous Quotes" },
  { text: "WHAT'S UP DOC", category: "Famous Quotes" },
  { text: "THE TRUTH IS OUT THERE", category: "Famous Quotes" },
  { text: "HERE'S JOHNNY", category: "Famous Quotes" },
  { text: "SAY HELLO TO MY LITTLE FRIEND", category: "Famous Quotes" },
  { text: "WHY SO SERIOUS", category: "Famous Quotes" },
  { text: "I VOLUNTEER AS TRIBUTE", category: "Famous Quotes" },
  { text: "THIS IS THE WAY", category: "Famous Quotes" },
  { text: "I AM GROOT", category: "Famous Quotes" },
  { text: "WEVE GOT TO GO BACK", category: "Famous Quotes" },
  { text: "DO OR DO NOT THERE IS NO TRY", category: "Famous Quotes" },
  { text: "WE ARE NOT IN KANSAS ANYMORE", category: "Famous Quotes" },
  { text: "YOU TALKING TO ME", category: "Famous Quotes" },
  { text: "I COULD HAVE BEEN A CONTENDER", category: "Famous Quotes" },
  { text: "HERE IS LOOKING AT YOU KID", category: "Famous Quotes" },
  { text: "GO AHEAD MAKE MY DAY", category: "Famous Quotes" },
  { text: "THERE IS NO CRYING IN BASEBALL", category: "Famous Quotes" },
  { text: "THE NAME IS BOND JAMES BOND", category: "Famous Quotes" },
  { text: "ET PHONE HOME", category: "Famous Quotes" },
  { text: "ROADS WHERE WE ARE GOING WE DONT NEED ROADS", category: "Famous Quotes" },
  { text: "KEEP YOUR FRIENDS CLOSE", category: "Famous Quotes" },
  { text: "I FEEL THE NEED FOR SPEED", category: "Famous Quotes" },
  { text: "YOU HAD ME AT HELLO", category: "Famous Quotes" },
  { text: "HOPE IS A GOOD THING", category: "Famous Quotes" },
  { text: "CARPE DIEM SEIZE THE DAY", category: "Famous Quotes" },
  { text: "THAT WILL DO PIG THAT WILL DO", category: "Famous Quotes" },
  { text: "MY PRECIOUS", category: "Famous Quotes" },
  { text: "OGRES ARE LIKE ONIONS", category: "Famous Quotes" },
  { text: "FISH ARE FRIENDS NOT FOOD", category: "Famous Quotes" },
  { text: "TO THE STARS AND BEYOND", category: "Famous Quotes" },

  // ──────────────────────────────────────────
  // Song Lyrics (new batch)
  // ──────────────────────────────────────────
  { text: "HOTEL CALIFORNIA", category: "Song Lyrics" },
  { text: "LIVING ON A PRAYER", category: "Song Lyrics" },
  { text: "UNDER PRESSURE", category: "Song Lyrics" },
  { text: "ANOTHER ONE BITES THE DUST", category: "Song Lyrics" },
  { text: "BILLIE JEAN IS NOT MY LOVER", category: "Song Lyrics" },
  { text: "HEY JUDE", category: "Song Lyrics" },
  { text: "I WANT TO HOLD YOUR HAND", category: "Song Lyrics" },
  { text: "BORN TO RUN", category: "Song Lyrics" },
  { text: "PURPLE RAIN", category: "Song Lyrics" },
  { text: "LIKE A ROLLING STONE", category: "Song Lyrics" },
  { text: "SMELLS LIKE TEEN SPIRIT", category: "Song Lyrics" },
  { text: "NOTHING ELSE MATTERS", category: "Song Lyrics" },
  { text: "WELCOME TO THE JUNGLE", category: "Song Lyrics" },
  { text: "SWEET CHILD O MINE", category: "Song Lyrics" },
  { text: "CRAZY TRAIN", category: "Song Lyrics" },
  { text: "OLD TOWN ROAD", category: "Song Lyrics" },
  { text: "UPTOWN FUNK", category: "Song Lyrics" },
  { text: "ROLLING IN THE DEEP", category: "Song Lyrics" },
  { text: "JUST DANCE", category: "Song Lyrics" },
  { text: "THUNDER ROAD", category: "Song Lyrics" },
  { text: "DONT STOP ME NOW", category: "Song Lyrics" },
  { text: "POUR SOME SUGAR ON ME", category: "Song Lyrics" },
  { text: "PAINT IT BLACK", category: "Song Lyrics" },
  { text: "FREE BIRD", category: "Song Lyrics" },
  { text: "WISH YOU WERE HERE", category: "Song Lyrics" },
  { text: "COME TOGETHER RIGHT NOW", category: "Song Lyrics" },
  { text: "WE ARE THE WORLD", category: "Song Lyrics" },
  { text: "I WILL ALWAYS LOVE YOU", category: "Song Lyrics" },
  { text: "WHAT A FEELING", category: "Song Lyrics" },
  { text: "TOTAL ECLIPSE OF THE HEART", category: "Song Lyrics" },
  { text: "EYE OF THE TIGER", category: "Song Lyrics" },
  { text: "GIRLS JUST WANT TO HAVE FUN", category: "Song Lyrics" },
  { text: "TAKE ON ME", category: "Song Lyrics" },
  { text: "EVERY ROSE HAS ITS THORN", category: "Song Lyrics" },
  { text: "DONT WORRY BE HAPPY", category: "Song Lyrics" },
  { text: "RESPECT FIND OUT WHAT IT MEANS TO ME", category: "Song Lyrics" },
  { text: "STAND BY ME", category: "Song Lyrics" },
  { text: "MY GIRL", category: "Song Lyrics" },
  { text: "AINT NO SUNSHINE", category: "Song Lyrics" },
  { text: "SUPERSTITION", category: "Song Lyrics" },

  // ──────────────────────────────────────────
  // History (new batch)
  // ──────────────────────────────────────────
  { text: "THE CIVIL WAR", category: "History" },
  { text: "THE ROMAN EMPIRE", category: "History" },
  { text: "THE RENAISSANCE", category: "History" },
  { text: "WORLD WAR TWO", category: "History" },
  { text: "THE COLD WAR", category: "History" },
  { text: "THE FRENCH REVOLUTION", category: "History" },
  { text: "THE MAGNA CARTA", category: "History" },
  { text: "THE BATTLE OF GETTYSBURG", category: "History" },
  { text: "THE OREGON TRAIL", category: "History" },
  { text: "THE GREAT DEPRESSION", category: "History" },
  { text: "THE BERLIN WALL", category: "History" },
  { text: "THE EMANCIPATION PROCLAMATION", category: "History" },
  { text: "THE ROARING TWENTIES", category: "History" },
  { text: "THE LOUISIANA PURCHASE", category: "History" },
  { text: "MANIFEST DESTINY", category: "History" },
  { text: "THE TRAIL OF TEARS", category: "History" },
  { text: "THE ALAMO", category: "History" },
  { text: "THE SUFFRAGE MOVEMENT", category: "History" },
  { text: "PROHIBITION ERA", category: "History" },
  { text: "THE MARSHALL PLAN", category: "History" },
  { text: "THE CUBAN MISSILE CRISIS", category: "History" },
  { text: "WATERGATE SCANDAL", category: "History" },
  { text: "THE SPACE RACE", category: "History" },
  { text: "FALL OF THE BERLIN WALL", category: "History" },
  { text: "THE IRISH POTATO FAMINE", category: "History" },
  { text: "THE SPANISH ARMADA", category: "History" },
  { text: "GUTENBERG PRINTING PRESS", category: "History" },
  { text: "SIGNING OF THE CONSTITUTION", category: "History" },
  { text: "LEWIS AND CLARK EXPEDITION", category: "History" },
  { text: "D-DAY NORMANDY INVASION", category: "History" },
  { text: "THE BLACK PLAGUE", category: "History" },
  { text: "THE OTTOMAN EMPIRE", category: "History" },
  { text: "COLOMBUS SAILS THE OCEAN", category: "History" },
  { text: "THE BRONZE AGE", category: "History" },
  { text: "BATTLE OF WATERLOO", category: "History" },
  { text: "THE HUNDRED YEARS WAR", category: "History" },
  { text: "CLEOPATRA OF EGYPT", category: "History" },
  { text: "ALEXANDER THE GREAT", category: "History" },
  { text: "GENGHIS KHAN", category: "History" },
  { text: "THE MONGOL EMPIRE", category: "History" },

  // ──────────────────────────────────────────
  // Places (new batch)
  // ──────────────────────────────────────────
  { text: "THE COLOSSEUM", category: "Places" },
  { text: "LAS VEGAS STRIP", category: "Places" },
  { text: "YELLOWSTONE NATIONAL PARK", category: "Places" },
  { text: "BUCKINGHAM PALACE", category: "Places" },
  { text: "AMAZON RAINFOREST", category: "Places" },
  { text: "TAJ MAHAL", category: "Places" },
  { text: "MACHU PICCHU", category: "Places" },
  { text: "CHICHEN ITZA", category: "Places" },
  { text: "ANGKOR WAT", category: "Places" },
  { text: "SYDNEY OPERA HOUSE", category: "Places" },
  { text: "THE DEAD SEA", category: "Places" },
  { text: "PANAMA CANAL", category: "Places" },
  { text: "THE FRENCH RIVIERA", category: "Places" },
  { text: "EASTER ISLAND", category: "Places" },
  { text: "GALAPAGOS ISLANDS", category: "Places" },
  { text: "VICTORIA FALLS", category: "Places" },
  { text: "MOUNT KILIMANJARO", category: "Places" },
  { text: "STONEHENGE", category: "Places" },
  { text: "HOLLYWOOD WALK OF FAME", category: "Places" },
  { text: "BOURBON STREET", category: "Places" },
  { text: "WAIKIKI BEACH", category: "Places" },
  { text: "MOUNT FUJI", category: "Places" },
  { text: "THE SWISS ALPS", category: "Places" },
  { text: "VENICE CANALS", category: "Places" },
  { text: "GREAT SMOKY MOUNTAINS", category: "Places" },
  { text: "ALCATRAZ ISLAND", category: "Places" },
  { text: "HOOVER DAM", category: "Places" },
  { text: "CARLSBAD CAVERNS", category: "Places" },
  { text: "GLACIER NATIONAL PARK", category: "Places" },
  { text: "REDWOOD NATIONAL FOREST", category: "Places" },
  { text: "THE ACROPOLIS", category: "Places" },
  { text: "NIAGARA ON THE LAKE", category: "Places" },
  { text: "TRAFALGAR SQUARE", category: "Places" },
  { text: "BOURBON TRAIL", category: "Places" },
  { text: "MARDI GRAS NEW ORLEANS", category: "Places" },
  { text: "SANTORINI GREECE", category: "Places" },
  { text: "NORTHERN CALIFORNIA COAST", category: "Places" },
  { text: "YELLOWSTONE GEYSER", category: "Places" },
  { text: "GRAND TETON MOUNTAINS", category: "Places" },
  { text: "MISSISSIPPI RIVER", category: "Places" },

  // ──────────────────────────────────────────
  // Idioms (new batch)
  // ──────────────────────────────────────────
  { text: "BREAK THE ICE", category: "Idioms" },
  { text: "BURNING BRIDGES", category: "Idioms" },
  { text: "CUTTING CORNERS", category: "Idioms" },
  { text: "DON'T JUDGE A BOOK BY ITS COVER", category: "Idioms" },
  { text: "JUMP ON THE BANDWAGON", category: "Idioms" },
  { text: "KEEP YOUR CHIN UP", category: "Idioms" },
  { text: "STEAL SOMEONES THUNDER", category: "Idioms" },
  { text: "TAKE IT WITH A GRAIN OF SALT", category: "Idioms" },
  { text: "THE EARLY BIRD GETS THE WORM", category: "Idioms" },
  { text: "TIP OF THE ICEBERG", category: "Idioms" },
  { text: "TURN A BLIND EYE", category: "Idioms" },
  { text: "WHOLE NINE YARDS", category: "Idioms" },
  { text: "CRY OVER SPILLED MILK", category: "Idioms" },
  { text: "IT TAKES TWO TO TANGO", category: "Idioms" },
  { text: "BACK TO SQUARE ONE", category: "Idioms" },
  { text: "BEAT AROUND THE BUSH", category: "Idioms" },
  { text: "BURNING THE CANDLE AT BOTH ENDS", category: "Idioms" },
  { text: "ELEPHANT IN THE ROOM", category: "Idioms" },
  { text: "GIVE THE COLD SHOULDER", category: "Idioms" },
  { text: "HIT THE GROUND RUNNING", category: "Idioms" },
  { text: "IN THE SAME BOAT", category: "Idioms" },
  { text: "KEEP IT UNDER YOUR HAT", category: "Idioms" },
  { text: "LET SLEEPING DOGS LIE", category: "Idioms" },
  { text: "MAKE A LONG STORY SHORT", category: "Idioms" },
  { text: "NOT MY CUP OF TEA", category: "Idioms" },
  { text: "OUT OF THE FRYING PAN", category: "Idioms" },
  { text: "READ BETWEEN THE LINES", category: "Idioms" },
  { text: "SITTING ON THE FENCE", category: "Idioms" },
  { text: "THE LAST STRAW", category: "Idioms" },
  { text: "UP IN THE AIR", category: "Idioms" },
  { text: "WATER UNDER THE BRIDGE", category: "Idioms" },
  { text: "YOU CAN SAY THAT AGAIN", category: "Idioms" },
  { text: "ADD INSULT TO INJURY", category: "Idioms" },
  { text: "BLOOD IS THICKER THAN WATER", category: "Idioms" },
  { text: "CAUGHT RED HANDED", category: "Idioms" },
  { text: "DONT PUT ALL YOUR EGGS IN ONE BASKET", category: "Idioms" },
  { text: "EVERY DOG HAS ITS DAY", category: "Idioms" },
  { text: "FIT AS A FIDDLE", category: "Idioms" },
  { text: "GET A TASTE OF YOUR OWN MEDICINE", category: "Idioms" },
  { text: "HAVE YOUR CAKE AND EAT IT TOO", category: "Idioms" },

  // ──────────────────────────────────────────
  // Pop Culture (new batch)
  // ──────────────────────────────────────────
  { text: "NETFLIX AND CHILL", category: "Pop Culture" },
  { text: "BINGE WATCHING", category: "Pop Culture" },
  { text: "REALITY TELEVISION", category: "Pop Culture" },
  { text: "SELFIE STICK", category: "Pop Culture" },
  { text: "VIRAL VIDEO", category: "Pop Culture" },
  { text: "ESCAPE ROOM", category: "Pop Culture" },
  { text: "COMIC CON", category: "Pop Culture" },
  { text: "SUPER BOWL HALFTIME SHOW", category: "Pop Culture" },
  { text: "RED CARPET", category: "Pop Culture" },
  { text: "EMMY AWARDS", category: "Pop Culture" },
  { text: "GRAMMY AWARDS", category: "Pop Culture" },
  { text: "OSCAR NIGHT", category: "Pop Culture" },
  { text: "BOX OFFICE HIT", category: "Pop Culture" },
  { text: "CHART TOPPING SINGLE", category: "Pop Culture" },
  { text: "SOLD OUT CONCERT", category: "Pop Culture" },
  { text: "FLASH MOB", category: "Pop Culture" },
  { text: "KARAOKE NIGHT", category: "Pop Culture" },
  { text: "DANCE BATTLE", category: "Pop Culture" },
  { text: "RAP BATTLE", category: "Pop Culture" },
  { text: "TALENT SHOW", category: "Pop Culture" },
  { text: "GAME SHOW", category: "Pop Culture" },
  { text: "TALK SHOW HOST", category: "Pop Culture" },
  { text: "LATE NIGHT COMEDY", category: "Pop Culture" },
  { text: "CELEBRITY CHEF", category: "Pop Culture" },
  { text: "FASHION WEEK", category: "Pop Culture" },
  { text: "COVER BAND", category: "Pop Culture" },
  { text: "FAN FICTION", category: "Pop Culture" },
  { text: "COSPLAY COSTUME", category: "Pop Culture" },
  { text: "MEET AND GREET", category: "Pop Culture" },
  { text: "BACKSTAGE PASS", category: "Pop Culture" },
  { text: "VIP SECTION", category: "Pop Culture" },
  { text: "AFTER PARTY", category: "Pop Culture" },
  { text: "BREAKING THE INTERNET", category: "Pop Culture" },
  { text: "BINGE WORTHY SERIES", category: "Pop Culture" },
  { text: "STREAMING SERVICE", category: "Pop Culture" },
  { text: "PODCAST EPISODE", category: "Pop Culture" },
  { text: "TRUE CRIME DOCUMENTARY", category: "Pop Culture" },
  { text: "UNBOXING VIDEO", category: "Pop Culture" },
  { text: "THROWBACK THURSDAY", category: "Pop Culture" },
  { text: "MEME OF THE YEAR", category: "Pop Culture" },

  // ──────────────────────────────────────────
  // Science & Nature (new batch)
  // ──────────────────────────────────────────
  { text: "BLACK HOLE", category: "Science & Nature" },
  { text: "SPEED OF LIGHT", category: "Science & Nature" },
  { text: "DNA DOUBLE HELIX", category: "Science & Nature" },
  { text: "THE BIG BANG", category: "Science & Nature" },
  { text: "TECTONIC PLATES", category: "Science & Nature" },
  { text: "FOSSIL FUELS", category: "Science & Nature" },
  { text: "RENEWABLE ENERGY", category: "Science & Nature" },
  { text: "CARBON FOOTPRINT", category: "Science & Nature" },
  { text: "CLIMATE CHANGE", category: "Science & Nature" },
  { text: "GREENHOUSE EFFECT", category: "Science & Nature" },
  { text: "ENDANGERED SPECIES", category: "Science & Nature" },
  { text: "NATURAL SELECTION", category: "Science & Nature" },
  { text: "MAGNETIC FIELD", category: "Science & Nature" },
  { text: "NUCLEAR FUSION", category: "Science & Nature" },
  { text: "ABSOLUTE ZERO", category: "Science & Nature" },
  { text: "SOUND WAVES", category: "Science & Nature" },
  { text: "ELECTRIC CURRENT", category: "Science & Nature" },
  { text: "CHEMICAL REACTION", category: "Science & Nature" },
  { text: "NEWTON'S LAWS OF MOTION", category: "Science & Nature" },
  { text: "THE DOPPLER EFFECT", category: "Science & Nature" },
  { text: "FIBONACCI SEQUENCE", category: "Science & Nature" },
  { text: "ARTIFICIAL INTELLIGENCE", category: "Science & Nature" },
  { text: "QUANTUM MECHANICS", category: "Science & Nature" },
  { text: "CONTINENTAL DRIFT", category: "Science & Nature" },
  { text: "ENDANGERED RAIN FOREST", category: "Science & Nature" },
  { text: "BUTTERFLY MIGRATION", category: "Science & Nature" },
  { text: "GREAT WHITE SHARK", category: "Science & Nature" },
  { text: "HUMPBACK WHALE", category: "Science & Nature" },
  { text: "KOMODO DRAGON", category: "Science & Nature" },
  { text: "EMPEROR PENGUIN", category: "Science & Nature" },
  { text: "VENUS FLY TRAP", category: "Science & Nature" },
  { text: "GIANT SEQUOIA", category: "Science & Nature" },
  { text: "ACTIVE VOLCANO", category: "Science & Nature" },
  { text: "EARTHQUAKE FAULT LINE", category: "Science & Nature" },
  { text: "SUPERNOVA EXPLOSION", category: "Science & Nature" },
  { text: "HUBBLE SPACE TELESCOPE", category: "Science & Nature" },
  { text: "INTERNATIONAL SPACE STATION", category: "Science & Nature" },
  { text: "MARS ROVER", category: "Science & Nature" },
  { text: "AURORA BOREALIS", category: "Science & Nature" },
  { text: "MILKY WAY CONSTELLATION", category: "Science & Nature" },

  // ──────────────────────────────────────────
  // Sports (new batch)
  // ──────────────────────────────────────────
  { text: "SUPER BOWL SUNDAY", category: "Sports" },
  { text: "WORLD SERIES", category: "Sports" },
  { text: "SLAM DUNK", category: "Sports" },
  { text: "TOUCHDOWN PASS", category: "Sports" },
  { text: "MARATHON RUNNER", category: "Sports" },
  { text: "TRIPLE CROWN", category: "Sports" },
  { text: "GRAND SLAM", category: "Sports" },
  { text: "PENALTY KICK", category: "Sports" },
  { text: "OVERTIME THRILLER", category: "Sports" },
  { text: "SEVENTH INNING STRETCH", category: "Sports" },
  { text: "FIRST DOWN", category: "Sports" },
  { text: "THREE POINT SHOT", category: "Sports" },
  { text: "BUZZER BEATER", category: "Sports" },
  { text: "HIGH JUMP", category: "Sports" },
  { text: "LONG JUMP", category: "Sports" },
  { text: "FIGURE SKATING", category: "Sports" },
  { text: "DOWNHILL SKIING", category: "Sports" },
  { text: "BATTING AVERAGE", category: "Sports" },
  { text: "PERFECT GAME", category: "Sports" },
  { text: "NO HITTER", category: "Sports" },
  { text: "FAST BREAK", category: "Sports" },
  { text: "FULL COURT PRESS", category: "Sports" },
  { text: "HAIL MARY PASS", category: "Sports" },
  { text: "WORLD RECORD", category: "Sports" },
  { text: "CLOSING CEREMONY", category: "Sports" },
  { text: "CHAMPIONSHIP RING", category: "Sports" },
  { text: "HALFTIME SHOW", category: "Sports" },
  { text: "SUDDEN DEATH", category: "Sports" },
  { text: "PUNT RETURN", category: "Sports" },
  { text: "ALLEY OOP", category: "Sports" },
  { text: "PICK AND ROLL", category: "Sports" },
  { text: "POWER PLAY GOAL", category: "Sports" },
  { text: "GRAND PRIX WINNER", category: "Sports" },
  { text: "CHECKERED FLAG", category: "Sports" },
  { text: "BOXING RING", category: "Sports" },
  { text: "KNOCKOUT PUNCH", category: "Sports" },
  { text: "GOAL LINE STAND", category: "Sports" },
  { text: "UNDEFEATED SEASON", category: "Sports" },
  { text: "BENCH PRESS", category: "Sports" },
  { text: "EXTRA INNINGS", category: "Sports" },
];
